apiVersion: v1
baseDomain: example.com
metadata:
  name: my-openshift-cluster
platform:
  aws:
    region: us-east-1
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"<your_pull_secret>"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr... your_ssh_key_here
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
controlPlane:
  name: master
  replicas: 3
  platform:
    aws:
      type: m5.xlarge
compute:
- name: worker
  replicas: 3
  platform:
    aws:
      type: m5.large