---
- name: Setup local environment
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - git
          - curl
          - vim
        state: present

    - name: Ensure Python is installed
      apt:
        name: python3
        state: present

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install Ansible via pip
      pip:
        name: ansible
        executable: pip3